version: '3.8'

services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser1234
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  gestao-db:
    image: postgres:16
    container_name: gestao-db
    environment:
      POSTGRES_DB: gestaodb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser1234
    ports:
      - "5433:5432"
    volumes:
      - gestao-db-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devuser1234
      SERVER_PORT: 8080

  transaction-api:
    container_name: transaction-api
    build:
      context: ./transaction-api
    ports:
      - "8081:8080"
    depends_on:
      - gestao-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gestao-db:5432/gestaodb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devuser1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080

  processor-worker:
    container_name: processor-worker
    build:
      context: ./processor-worker
    ports:
      - "8082:8080"
    depends_on:
      - gestao-db
      - kafka
      - transaction-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gestao-db:5432/gestaodb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devuser1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080

volumes:
  user-db-data:
  gestao-db-data:
  kafka-data: